using System;
using NUnit.Framework;
using MainPart.Files;
using Moq;
using System.Collections.Generic;

[TestFixture]
class Example1Test
{
    private Mock<IDisposable> _s;
    private Mock<ICloneable> _c;
    private Example1 _example1;
    [SetUp]
    public void SetUp()
    {
        var a = default(int);
        var str = default(string);
        _s = new Mock<IDisposable>();
        _c = new Mock<ICloneable>();
        _example1 = new Example1(_s.Object, _c.Object, a, str);
    }

    [Test]
    public void Function1()
    {
        var d = default(int);
        var e = default(int);
        var actual = _example1.Function1(d, e);
        var expected = default(int);
        Assert.That(actual, Is.EqualTo(expected));
        Assert.Fail("autogenerated");
    }

    [Test]
    public void Function2()
    {
        _example1.Function2();
        Assert.Fail("autogenerated");
    }
}